name: GA0 Test Workflow

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 23f2003326@ds.study.iitm.ac.in
        run: echo "Hello, world!"

      - name: Finish
        run: echo "Workflow completed"
